name: Commit
on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22, 23]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # 4.0.3
        with:
            node-version: ${{ matrix.node-version }}
            cache: npm
      - name: cache package-policy
        uses: actions/cache@v4
        with:
          path: ~/.package-policy
          key: package-policy-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            package-policy-cache-
      - name: Installing dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Typecheck
        run: npx tsc
      - name: Format
        run: npx prettier --check ./lib
      - name: Run package-policy
        run: node . . ./test
